#!/bin/bash   

#working directory @ miZeOS
mkdir miZeOS
cd miZeOS
#get git content:
git init
git config --global user.name "MisterBigThor"
git config --global user.email "vcr97@gmail.com"
git remote add origin https://github.com/MisterBigThor/so2FIB.git
git pull origin master

#store password:
git config credential.helper store

#sym link for testing
ln -s E1/libjp1.a libjp1.a
