/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Dominio.xCtrlDominioJoc;
import Dominio.xCtrlDominioProblemas;
import Dominio.xCtrlDominioUsuario;

import javax.swing.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Marc
 */
public class CustomGameScreen extends javax.swing.JFrame {

    private xCtrlDominioUsuario usr;
    private xCtrlDominioProblemas prb;

    /**
     * Creates new form CustomGameScreen
     */
    public CustomGameScreen(xCtrlDominioProblemas ps, xCtrlDominioUsuario usr2) {
        if(ps == null){
            this.prb = new xCtrlDominioProblemas();
            try { prb.iniciarControlador(); } catch (Exception e) { e.printStackTrace(); }
        }
        else this.prb = ps;
        if(usr2 == null){
            this.usr = new xCtrlDominioUsuario();
            this.usr.iniciarControlador();
            this.usr.entrarConUsuario();
        }
        //this.usr.iniciarControlador();

        //this.usr.entrarConUsuario();
        else this.usr = usr2;
        initComponents();

        lstAtacante.add(usr.getUsuarioActual());
        lstAtacante.add(xCtrlDominioJoc.INVITADO);
        lstAtacante.add(xCtrlDominioJoc.IASIMPLE);
        lstAtacante.add(xCtrlDominioJoc.IASUPERIOR);

        lstDefensor.add(usr.getUsuarioActual());
        lstDefensor.add(xCtrlDominioJoc.INVITADO);
        lstDefensor.add(xCtrlDominioJoc.IASIMPLE);
        lstDefensor.add(xCtrlDominioJoc.IASUPERIOR);

        //this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        //this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        for (String s : prb.getIdProblemas()) lstProblema.add(s);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lstAtacante = new java.awt.Choice();
        lstProblema = new java.awt.Choice();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lstDefensor = new java.awt.Choice();
        btnJugar = new javax.swing.JButton();

        jButton2.setText("jButton2");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Atacante:");

        jLabel2.setText("Problema:");

        jLabel3.setText("Defensor:");

        btnJugar.setText("Jugar");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lstProblema, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel2))
                            .addComponent(lstAtacante, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel3)
                                        .addGap(33, 33, 33))
                                    .addComponent(lstDefensor, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                                .addComponent(btnJugar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lstAtacante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lstDefensor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJugar))
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lstProblema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt)  {//GEN-FIRST:event_btnJugarActionPerformed
        
        String a = lstAtacante.getSelectedItem();
        String d = lstDefensor.getSelectedItem();
        String p = lstProblema.getSelectedItem();

        if(a.equals(usr.getUsuarioActual())) a = xCtrlDominioJoc.PERSONA;
        if(d.equals(usr.getUsuarioActual())) d = xCtrlDominioJoc.PERSONA;
        if(a.equals(xCtrlDominioJoc.PERSONA) && d.equals(xCtrlDominioJoc.PERSONA)) d = xCtrlDominioJoc.INVITADO;

        xCtrlDominioJoc CDJ;
        try {
            this.dispose();
            CDJ = new xCtrlDominioJoc(p, a, d, this.usr);
            Game g = new Game(CDJ);
            g.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            g.pack();
            g.setTitle(a + " vs. " + d);
            g.setLocationRelativeTo(null);
            g.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_btnJugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomGameScreen(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private java.awt.Choice lstAtacante;
    private java.awt.Choice lstDefensor;
    private java.awt.Choice lstProblema;
    // End of variables declaration//GEN-END:variables
}


