/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Dominio.xCtrlDominioUsuario;
import Dominio.Usuario;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;

/**
 *
 * @author Marc
 */
public class LogInScreen extends javax.swing.JPanel {

    /**
     * Creates new form LogInScreen
     */
    private static JFrame jf;
    private xCtrlDominioUsuario CdU;
    
    public LogInScreen(xCtrlDominioUsuario domUsuario) {

        if(domUsuario != null) this.CdU = domUsuario;
        else{
            this.CdU = new xCtrlDominioUsuario();
            CdU.iniciarControlador();
        }
        initComponents();
    }
    
    protected static void createAndShowUI() {
        JFrame frame = new JFrame("Splash Screen");
        jf = frame;
        frame.getContentPane().add(new LogInScreen(null));
        frame.setSize(0, 0);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                createAndShowUI();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUser = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogIn = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();

        lblUser.setText("Usuario:");

        lblPassword.setText("Contraseña:");

        txtUser.setName("txtUser"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PROJECTE ESCACS");

        btnLogIn.setText("Log In");
        btnLogIn.setName("btnLogIn"); // NOI18N
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });
        btnRegister.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(ActionEvent e) {registrarNouUsuari(e);}
        });
        btnRegister.setText("Register");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUser)
                            .addComponent(lblPassword))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtPassword))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogIn)
                        .addGap(78, 78, 78)
                        .addComponent(btnRegister)))
                .addGap(0, 100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogIn)
                    .addComponent(btnRegister))
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        // TODO add your handling code here:
        String usr = txtUser.getText().trim();
        char[] pwd = txtPassword.getPassword();
        if (ComprobarSintaxis(usr, String.valueOf(pwd))) return;
        boolean registeredUser = CdU.logInUsuario(usr, pwd);
        
        if (registeredUser){
            jf.dispose();
            JFrame frame = new JFrame("Welcome " + CdU.getUsuarioActual());
            frame.getContentPane().add(new WelcomeScreen(frame, CdU));
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "Usuario y contraseña incorrectos.");
            txtPassword.setText("");
        }
    }//GEN-LAST:event_btnLogInActionPerformed

    private void registrarNouUsuari(java.awt.event.ActionEvent evt) {
        String usr = txtUser.getText().trim();
        char[] pwd = txtPassword.getPassword();
        String pass = String.valueOf(pwd);
        System.out.println(pass);
        if (ComprobarSintaxis(usr, pass)) return;
        System.out.println(pass);
        try {
            String apodo = JOptionPane.showInputDialog( "Usuario " + usr + " creado con exito, introduza un apoodo");
            CdU.altaUsuario(usr, apodo, pass);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al crear el usuario");
            txtPassword.setText("");
        }

    }

    private boolean ComprobarSintaxis(String usr, String pass) {
        if(usr.equals("")) {JOptionPane.showMessageDialog(this, "Parametros incorrectos");
            return true;
        }

        if(pass.equals("")) {JOptionPane.showMessageDialog(this, "Parametros incorrectos");
            return true;
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
