/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Dominio.*;

import PiezasBlancas.cargaPiezasBlancas;
import PiezasNegras.cargaPiezasNegras;

import java.awt.image.BufferedImage;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;


/**
 *
 * @author Marc
 */
public class WelcomeScreen extends javax.swing.JPanel {

    private JFrame myJFrame;
    private xCtrlDominioUsuario CdU;
    /**
     * Creates new form WelcomeScreen
     */
    public WelcomeScreen(JFrame jf, xCtrlDominioUsuario cdu) {
        this.myJFrame = jf;
        this.CdU = cdu;
        initComponents();
        try{

            BufferedImage image = ImageIO.read(new cargaPiezasBlancas().getBishop());
            BufferedImage image2 = ImageIO.read(new cargaPiezasNegras().getPawn());
            //lblLeftIcon.add(new JLabel(new ImageIcon(image.getScaledInstance(50,50,1))));
            //lblRightIcon.add(new JLabel(new ImageIcon(image2.getScaledInstance(50,50,1))));
            lblLeftIcon.setIcon(new ImageIcon(image.getScaledInstance(50,50,1)));
            lblRightIcon.setIcon(new ImageIcon(image2.getScaledInstance(50,50,1)));
        }
        catch (Exception ex){
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        btnProblemas = new javax.swing.JButton();
        btnPartida = new javax.swing.JButton();
        btnRanking = new javax.swing.JButton();
        lblLeftIcon = new javax.swing.JLabel();
        lblRightIcon = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 200));

        lblWelcome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblWelcome.setText("Welcome");

        btnProblemas.setText("Problemas");
        btnProblemas.setPreferredSize(new java.awt.Dimension(100, 25));
        btnProblemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProblemasActionPerformed(evt);
            }
        });

        btnPartida.setText("Jugar Partida");
        btnPartida.setPreferredSize(new java.awt.Dimension(100, 25));
        btnPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartidaActionPerformed(evt);
            }
        });

        btnRanking.setText("Ranking");
        btnRanking.setPreferredSize(new java.awt.Dimension(100, 25));
        btnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankingActionPerformed(evt);
            }
        });

        lblRightIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnProblemas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblLeftIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWelcome)
                    .addComponent(btnRanking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPartida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblRightIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblWelcome))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLeftIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRightIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProblemas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRanking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartidaActionPerformed
        //myJFrame.dispose();
        CustomGameScreen CGM = new CustomGameScreen(null, CdU);
        CGM.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        CGM.pack();
        CGM.setTitle("¡Configura tu partida!");
        CGM.setLocationRelativeTo(null);
        CGM.setVisible(true);
    }//GEN-LAST:event_btnPartidaActionPerformed

    private void btnProblemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProblemasActionPerformed
        //myJFrame.dispose();
        try {
            VistaProblema VP = new VistaProblema(null);
            VP.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            VP.pack();
            VP.setTitle("Creador de problemas");
            VP.setLocationRelativeTo(null);
            VP.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(WelcomeScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnProblemasActionPerformed

    private void btnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankingActionPerformed
        //myJFrame.dispose();
        try {
            VistaRanking VR =  new VistaRanking(null,CdU);
            VR.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            VR.pack();
            VR.setTitle("Ranking");
            VR.setLocationRelativeTo(null);
            VR.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(WelcomeScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRankingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPartida;
    private javax.swing.JButton btnProblemas;
    private javax.swing.JButton btnRanking;
    private javax.swing.JLabel lblLeftIcon;
    private javax.swing.JLabel lblRightIcon;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
