#!/bin/bash
echo ==============================
echo ==============================
javac Dominio/*.java
javac DriversDominio/*.java
javac Persistencia/*.java
javac Presentacion/*.java
javac PiezasNegras/*.java
javac PiezasBlancas/*.java

jar cvfm ajedrez.jar MANIFEST.MF Main.class Dominio/* Persistencia/* Presentacion/* PiezasNegras/* PiezasBlancas/*



